[package]
name = "satty"
version = "0.15.0"
edition = "2021"
authors = ["Matthias Gabriel <gabm+aur@mailbox.org>"]
description = "Modern Screenshot Annotation. A Screenshot Annotation Tool inspired by Swappy and Flameshot."
homepage = "https://github.com/gabm/satty"
repository = "https://github.com/gabm/satty"
license = "MPL-2.0"
include = [
  "src/**/*",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "assets/",
]


[dependencies]
relm4 = { version = "0.8", features = ["macros", "libadwaita", "gnome_42"] }
tokio = { version = "1.32.0", features = ["full"] }
gdk-pixbuf = "0.19.2"

# error handling
anyhow = "1.0"
thiserror = "1.0"

# command line
clap = { version = "4.4.10", features = ["derive"] }

# configuration file
xdg = "^2.5"
toml = "0.8.8"
serde = "1.0"
serde_derive = "1.0"
hex_color = {version = "3", features = ["serde"]}
chrono = "0.4.31"

# opengl rendering backend
femtovg = "0.8"
libloading = "0.8"
epoxy = "0.1.0"
glow = "0.13.1"
glib-macros = "0.19.2"
glib = "0.19.2"
resource = "0.5.0"  # font emedding
fontconfig = "0.8.0"  # font loading

[dependencies.relm4-icons]
version = "0.8.2"


[build-dependencies]
clap = { version = "4.4.10", features = ["derive"] }
clap_complete = "4.4.4"
clap_complete_nushell = "4.4.2"
clap_complete_fig = "4.4.2"
